name: Check Syllabus Update
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install deps
        run: yarn

      - name: run check
        working-directory: ./packages/syllabus-site
        env:
          DISCORD_WEB_HOOK: ${{ secrets.DISCORD_WEB_HOOK }}
        run: |
          yarn check-data;
